# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Build.SourceVersion)
jobs:

- job: Windows
  timeoutInMinutes: 0
  pool:
    vmImage: 'vs2017-win2016'

  variables:
    STAGING_DIRECTORY: C:\Users\VssAdministrator\STAGING
    STAGING_DIRECTORY_UNIX: /C/Users/VssAdministrator/STAGING
    ESY__CACHE_INSTALL_PATH: /C/Users/VssAdministrator/.esy/3_/i
    ESY__CACHE_SOURCE_TARBALL_PATH: /C/Users/VssAdministrator/.esy/source/i
    # ESY__NPM_ROOT: /C/npm/prefix/node_modules/esy

  steps:
  - template: .ci/use-node.yml
  - template: .ci/restore-build-cache.yml
  - script: npm install -g esy@0.5.6
    displayName: 'Install esy'
  - script: git clone https://github.com/bryphe/esy-bash
    displayName: 'Cloning esy-bash'
  - script: git checkout prometheansacrifice/bundle-python2.7
    displayName: 'Checkout python branch'
    workingDirectory: 'esy-bash'
  - script: npm i
    displayName: 'npm i'
    workingDirectory: 'esy-bash'
  - script: esy
    displayName: 'esy'
    workingDirectory: 'esy-bash/re'
  - script: npm run build-cygwin
    displayName: 'npm run build-cygwin'
    workingDirectory: 'esy-bash'
  - script: npm run package-cygwin
    displayName: 'npm run package-cygwin'
    workingDirectory: 'esy-bash'
  - script: node ./postinstall.js
    displayName: 'esy-bash postinstall'
    workingDirectory: 'esy-bash'
  - powershell: |
      $env:ESY__ESY_BASH = "$(Build.SourcesDirectory)\esy-bash"
      echo $env:ESY__ESY_BASH
      esy
      
    displayName: 'esy (with modified esy-bash)'
